import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
const root=path.resolve('.');
const dist=path.join(root,'dist');
const origin='https://katrosapaisagismo.com.br';
const pages=new Map(), assets=new Map(), failures=[];
const hosts=new Set(['katrosapaisagismo.com.br','www.katrosapaisagismo.com.br','katflores.com.br','www.katflores.com.br']);
const decode=s=>s.replaceAll('&amp;','&').replaceAll('&#038;','&').replaceAll('&#039;',"'").replaceAll('\\/','/');
function url(s,base){try {return new URL(decode(s),base)}catch{return null}}
function pageURL(s,base){const u=url(s,base);if(!u||!hosts.has(u.hostname)||/\.(?:jpg|jpeg|png|webp|gif|svg|pdf|xml|zip|css|js|ico|woff2?|ttf|mp4)$/i.test(u.pathname)||/\/(?:wp-|feed|comments)|replytocom/.test(u.pathname+u.search)||u.search)return null;return origin+u.pathname;}
async function get(u){const key=crypto.createHash('sha256').update(u).digest('hex');const f=path.resolve('.cache',key);try{return await fs.readFile(f)}catch{};const res=await fetch(u,{signal:AbortSignal.timeout(25000)});if(!res.ok)throw Error(res.status+' '+u);const b=Buffer.from(await res.arrayBuffer());if(b.length>25e6)throw Error('oversize '+u);await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f,b);return b;}
async function batch(items,fn,n=6){let cursor=0;await Promise.all(Array.from({length:n},async()=>{while(cursor<items.length){const x=items[cursor++];await fn(x);}}));}
function assetURL(s,base){const u=url(s,base);if(!u||!['http:','https:'].includes(u.protocol))return null;if(!/\.(?:css|js|jpg|jpeg|png|gif|svg|webp|ico|woff2?|ttf|eot|otf|mp4|pdf)(?:$|[?#])/i.test(u.href)&&u.hostname!=='fonts.googleapis.com')return null;u.hash='';return u.href;}
function addAsset(s,base){const u=assetURL(s,base);if(!u||assets.has(u))return;let ext=path.extname(new URL(u).pathname);if(!ext||ext.length>6)ext='.css';const name=crypto.createHash('sha256').update(u).digest('hex').slice(0,18)+ext;assets.set(u,{local:'/assets/'+name,done:false});}
function scanAssets(s,base,css=false){for(const m of s.matchAll(/https?:[^\s<>"'()]+/g))addAsset(m[0],base);for(const m of s.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g))addAsset(m[1],base);if(!css){for(const m of s.matchAll(/(?:src|href|data-src|data-bg|poster)\s*=\s*["']([^"']+)["']/g))addAsset(m[1],base);for(const m of s.matchAll(/srcset\s*=\s*["']([^"']+)["']/g))for(const p of m[1].split(','))addAsset(p.trim().split(/\s+/)[0],base);}}
let queue=[origin+'/'];
while(queue.length){const next=[];await batch(queue,async u=>{if(pages.has(u))return;pages.set(u,null);try{const s=(await get(u)).toString('utf8');if(!/<html/i.test(s))throw Error('not html');pages.set(u,s);scanAssets(s,u);for(const m of s.matchAll(/<a\b[^>]*\bhref\s*=\s*["']([^"']+)["']/gi)){const p=pageURL(m[1],u);if(p&&!pages.has(p)&&!next.includes(p))next.push(p);} }catch(e){failures.push({url:u,error:String(e)});}});console.log('Pages',pages.size,'assets discovered',assets.size);queue=next;}
await fs.mkdir(path.join(dist,'assets'),{recursive:true});
while([...assets.values()].some(a=>!a.done)){const pending=[...assets].filter(([,a])=>!a.done);await batch(pending,async([u,a])=>{a.done=true;try{let b;try{b=await get(u)}catch(e){const pu=new URL(u);if(hosts.has(pu.hostname)&&pu.hostname!=='katrosapaisagismo.com.br')b=await get(origin+pu.pathname+pu.search);else throw e;}a.bytes=b.length;a.buffer=b;if(a.local.endsWith('.css'))scanAssets(b.toString('utf8'),u,true);}catch(e){a.failed=true;failures.push({url:u,error:String(e)});}});console.log('Assets fetched',assets.size,'failures',failures.length);}
function replaceAssets(s,base){for(const [u,a]of assets){if(a.failed)continue;s=s.split(u).join(a.local).split(u.replaceAll('&','&amp;')).join(a.local).split(u.replaceAll('/','\\/')).join(a.local);}s=s.replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/g,(all,q,v)=>{const a=assets.get(assetURL(v,base));return a&&!a.failed?`url("${a.local}")`:all});return s;}
for(const [u,a]of assets){if(a.failed)continue;let b=a.buffer;if(a.local.endsWith('.css'))b=replaceAssets(b.toString('utf8'),u);await fs.writeFile(path.join(dist,a.local),b);delete a.buffer;}
for(const [u,raw]of pages){if(!raw)continue;let s=replaceAssets(raw,u);s=s.replace(/(<a\b[^>]*\bhref\s*=\s*)(["'])([^"']+)\2/gi,(all,p,q,v)=>{const dest=pageURL(v,u);if(dest&&pages.get(dest)){const h=url(v,u).hash;return p+q+new URL(dest).pathname+h+q}return all;});s=s.replace(/<link\b[^>]*(?:rel=['"](?:https:\/\/api.w.org\/|EditURI|shortlink|alternate)['"])[^>]*>/gi,'');s=s.replace(/<meta name=["']generator["'][^>]*>/gi,'');s=s.replace(/<script\b[^>]*>[\s\S]*?<\/script>/gi,t=>/googletagmanager\.com|Google Tag Manager|gtag\(/.test(t)?'':t);s=s.replace(/<noscript>\s*<iframe[^>]*googletagmanager[\s\S]*?<\/noscript>/gi,'');s=s.replace(/<img\b([^>]*?)>/gi,(all,a)=>{if(!/decoding=/.test(a))a+=' decoding="async"';return '<img'+a+'>';});s=s.replace('</head>','<meta name="robots" content="noindex, nofollow">\n</head>');const f=path.join(dist,decodeURIComponent(new URL(u).pathname),'index.html');await fs.mkdir(path.dirname(f),{recursive:true});await fs.writeFile(f,s);}
await fs.writeFile(path.join(root,'capture-report.json'),JSON.stringify({source:origin,capturedAt:new Date().toISOString(),pages:[...pages].filter(([,s])=>s).map(([u])=>new URL(u).pathname),assets:[...assets].map(([url,a])=>({url,...a})),failures},null,2));
console.log(JSON.stringify({pages:[...pages.values()].filter(Boolean).length,assets:[...assets.values()].filter(a=>!a.failed).length,failures:failures.length}));
